name: Release

on:
  push:
    tags:
      - "*"
    branches:
      - "develop"
      - "feature/*"

env:
  COMPOSER_FLAGS: --ansi --no-interaction --no-progress --no-suggest --prefer-dist --no-dev

jobs:
  build:
    name: Upload Release Asset

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4

    steps:
      - name: Get convenient env variables
        uses: FranzDiebold/github-env-vars-action@v1.2.1

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: soap
          ini-values: memory_limit=-1, phar.readonly=Off
          php-version: ${{ matrix.php-version }}

      - name: Display PHP Version
        run: php -v

      - name: Display release name
        run: echo $GITHUB_REF_NAME_SLUG

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get convenient Docker Meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: mikaelcom/wsdltophp

      - name: Install dependencies from composer.lock
        run: composer install ${{ env.COMPOSER_FLAGS }}

      - name: Validate composer.json
        run: composer validate

      - name: Install Box2
        run: curl -LSs https://box-project.github.io/box2/installer.php | php

      - name: Build phar file
        run: mkdir bin; php box.phar build

      - name: Display generated wsdltophp version
        run: php bin/wsdltophp.phar --version

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GITHUB_REF_NAME }}
          release_name: ${{ env.GITHUB_REF_NAME }}
          draft: true
          body: TODO

      - name: Upload phar to Github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/wsdltophp.phar
          asset_name: wsdltophp-${{ env.GITHUB_REF_NAME_SLUG }}.phar
          asset_content_type: application/octet-stream

      - name: Configure GPG key and sign phar
        run: |
          mkdir -p ~/.gnupg/
          chmod 0700 ~/.gnupg/
          echo "$GPG_SIGNING_KEY" > ~/.gnupg/private.key
          gpg --import ~/.gnupg/private.key
          gpg -u wsdltophp@mikael-delsol.fr --detach-sign --output wsdltophp.phar.asc ./bin/wsdltophp.phar
        env:
          GPG_SIGNING_KEY: |
            ${{ secrets.GPG_SIGNING_KEY_893E7553C4D525279BC8C6D9B41E3A1E3748D61F }}

      - name: Upload phar signature
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./wsdltophp.phar.asc
          asset_name: wsdltophp-${{ env.GITHUB_REF_NAME_SLUG }}.phar.asc
          asset_content_type: application/octet-stream

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build and push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: .github/Dockerfile
          build-args: |
            PHP=${{ matrix.php-version }}
            WSDLTOPHP=${{ env.GITHUB_REF_NAME }}
            PHAR=./bin/wsdltophp.phar
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
